### ISSUE TITLE
Golang race condition

### ISSUE THREAD

**Issue by ngoctint1lvc** [ngoctint1lvc/PayloadsAllTheThings#5]
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	c := make(chan int)
	var isDone bool
	// var mt sync.Mutex

	go func() {
		for {
			// mt.Lock()
			if !isDone {
				c <- 10
			}
			// mt.Unlock()
		}
	}()

	go func() {
		for {
			for v := range c {
				fmt.Printf("new value: %v\n", v)
			}
		}
	}()

	time.Sleep(time.Second * 1)

	// without locking, race condition bug will happen here!!!
	// mt.Lock()
	isDone = true
	close(c)
	// mt.Unlock()
	time.Sleep(time.Second * 1)
}

```

**Comment by ngoctint1lvc** [comment]
Output
```
new value: 10
new value: 10
new value: 10
panic: send on closed channel

goroutine 6 [running]:
main.main.func1(0xc0000140ef, 0xc000022120)
        /home/nt/Documents/tmp/hello.go:17 +0x45
created by main.main
        /home/nt/Documents/tmp/hello.go:13 +0x85
exit status 2
```
